stages:
  download:
    cmd: python src/download.py
    deps:
    - src/config.py
    - src/download.py
    - src/utils.py
    outs:
    - data/iris.csv
  plots:
    cmd: python src/plot.py
    deps:
    - src/config.py
    - src/plot.py
    - src/utils.py
    - data/iris.csv
    outs:
    - plots/matrix_plot.png
  evaluate:
    cmd: python src/fit_models.py
    params:
    - evaluate.model
    deps:
    - src/config.py
    - src/fit_models.py
    - src/utils.py
    - data/iris.csv
    metrics:
    - eval/metrics.json
plots:
  - plots/matrix_plot.png
